// flow-typed signature: 1249619d512778c210bf48e23944bc37
// flow-typed version: <<STUB>>/@lugia/lugia-complie_v^1.0.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/lugia-complie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/lugia-complie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/lugia-complie/bin/lugia-complie' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/BuildCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/CleanCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/Cmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/CoverCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/DevCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/FlowCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/GulpCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/gulpfile' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/helper' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/InstallCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/LintCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/PackCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/pkg' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/program' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/PublishCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/TestCmd' {
  declare module.exports: any;
}

declare module '@lugia/lugia-complie/lib/UnpublishCmd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/lugia-complie/bin/lugia-complie.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/bin/lugia-complie'>;
}
declare module '@lugia/lugia-complie/lib/BuildCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/BuildCmd'>;
}
declare module '@lugia/lugia-complie/lib/CleanCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/CleanCmd'>;
}
declare module '@lugia/lugia-complie/lib/Cmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/Cmd'>;
}
declare module '@lugia/lugia-complie/lib/CoverCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/CoverCmd'>;
}
declare module '@lugia/lugia-complie/lib/DevCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/DevCmd'>;
}
declare module '@lugia/lugia-complie/lib/FlowCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/FlowCmd'>;
}
declare module '@lugia/lugia-complie/lib/GulpCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/GulpCmd'>;
}
declare module '@lugia/lugia-complie/lib/gulpfile.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/gulpfile'>;
}
declare module '@lugia/lugia-complie/lib/helper.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/helper'>;
}
declare module '@lugia/lugia-complie/lib/InstallCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/InstallCmd'>;
}
declare module '@lugia/lugia-complie/lib/LintCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/LintCmd'>;
}
declare module '@lugia/lugia-complie/lib/PackCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/PackCmd'>;
}
declare module '@lugia/lugia-complie/lib/pkg.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/pkg'>;
}
declare module '@lugia/lugia-complie/lib/program.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/program'>;
}
declare module '@lugia/lugia-complie/lib/PublishCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/PublishCmd'>;
}
declare module '@lugia/lugia-complie/lib/TestCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/TestCmd'>;
}
declare module '@lugia/lugia-complie/lib/UnpublishCmd.js' {
  declare module.exports: $Exports<'@lugia/lugia-complie/lib/UnpublishCmd'>;
}
