// flow-typed signature: a8c1b8ec5f303461c9546ff530b43c20
// flow-typed version: <<STUB>>/@lugia/lugiax-core_v^1.0.1-4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/lugiax-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/lugiax-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/lugiax-core/flow-typed/npm/@lugia/jverify_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/@lugia/lugia-complie_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/autoprefixer_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/babel-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/case-sensitive-paths-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/chai_v4.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/chalk_v1.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/css-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/debug_v2.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/dotenv_v4.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/eslint-config-react-app_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/eslint-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/extract-text-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/file-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/fs-extra_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/global_v4.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/gulp_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/gulp-babel_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/gulp-changed_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/gulp-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/gulp-newer_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/gulp-rename_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/gulp-uglify_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/gulp-watch_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/html-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/identity-obj-proxy_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/immutable_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/install_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/isomorphic-fetch_v2.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/jest-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/jest-styled-components_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/jsdom_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/postcss-flexbugs-fixes_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/postcss-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/pump_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/raf_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/redux_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/redux-immutable_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/redux-saga_v0.16.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/shx_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/style-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/stylelint_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/stylelint-config-standard_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/stylelint-processor-styled-components_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/sw-precache-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/url-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/webpack-dev-server_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/webpack-manifest-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/flow-typed/npm/whatwg-fetch_vx.x.x' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/src/interface/lugiax-core.flow' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/src/lib/index' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/src/test/index.test' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/target/interface/lugiax-core.flow' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/target/lib/index' {
  declare module.exports: any;
}

declare module '@lugia/lugiax-core/target/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/lugiax-core/flow-typed/npm/@lugia/jverify_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/@lugia/jverify_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/@lugia/lugia-complie_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/@lugia/lugia-complie_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/autoprefixer_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/autoprefixer_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/babel-core_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/babel-eslint_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/babel-jest_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/babel-loader_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/babel-runtime_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/babel-runtime_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/case-sensitive-paths-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/case-sensitive-paths-webpack-plugin_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/chai_v4.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/chai_v4.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/chalk_v1.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/chalk_v1.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/cross-env_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/css-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/css-loader_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/debug_v2.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/debug_v2.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/dotenv_v4.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/dotenv_v4.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/enzyme_v3.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/eslint_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/eslint-config-react-app_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/eslint-config-react-app_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/eslint-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/eslint-loader_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/eslint-plugin-babel_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/eslint-plugin-flowtype_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/eslint-plugin-import_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/extract-text-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/extract-text-webpack-plugin_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/file-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/file-loader_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/flow-bin_v0.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/fs-extra_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/fs-extra_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/global_v4.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/global_v4.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/gulp_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/gulp_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/gulp-babel_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/gulp-babel_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/gulp-changed_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/gulp-changed_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/gulp-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/gulp-flowtype_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/gulp-newer_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/gulp-newer_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/gulp-rename_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/gulp-rename_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/gulp-uglify_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/gulp-uglify_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/gulp-watch_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/gulp-watch_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/html-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/html-webpack-plugin_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/husky_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/identity-obj-proxy_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/identity-obj-proxy_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/immutable_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/immutable_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/install_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/install_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/isomorphic-fetch_v2.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/isomorphic-fetch_v2.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/jest_v20.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/jest-cli_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/jest-cli_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/jest-styled-components_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/jest-styled-components_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/jsdom_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/jsdom_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/lint-staged_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/postcss-flexbugs-fixes_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/postcss-flexbugs-fixes_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/postcss-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/postcss-loader_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/prettier_v1.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/pump_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/pump_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/raf_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/raf_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/redux_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/redux_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/redux-immutable_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/redux-immutable_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/redux-saga_v0.16.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/redux-saga_v0.16.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/shx_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/shx_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/style-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/style-loader_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/stylelint_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/stylelint_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/stylelint-config-standard_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/stylelint-config-standard_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/stylelint-processor-styled-components_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/stylelint-processor-styled-components_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/sw-precache-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/sw-precache-webpack-plugin_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/url-loader_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/url-loader_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/webpack_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/webpack-dev-server_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/webpack-dev-server_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/webpack-manifest-plugin_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/webpack-manifest-plugin_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/flow-typed/npm/whatwg-fetch_vx.x.x.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/flow-typed/npm/whatwg-fetch_vx.x.x"
  >;
}
declare module '@lugia/lugiax-core/src/interface/lugiax-core.flow.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/src/interface/lugiax-core.flow"
  >;
}
declare module '@lugia/lugiax-core/src/lib/index.js' {
  declare module.exports: $Exports<"@lugia/lugiax-core/src/lib/index">;
}
declare module '@lugia/lugiax-core/src/test/index.test.js' {
  declare module.exports: $Exports<"@lugia/lugiax-core/src/test/index.test">;
}
declare module '@lugia/lugiax-core/target/interface/lugiax-core.flow.js' {
  declare module.exports: $Exports<
    "@lugia/lugiax-core/target/interface/lugiax-core.flow"
  >;
}
declare module '@lugia/lugiax-core/target/lib/index.js' {
  declare module.exports: $Exports<"@lugia/lugiax-core/target/lib/index">;
}
declare module '@lugia/lugiax-core/target/test/index.test.js' {
  declare module.exports: $Exports<"@lugia/lugiax-core/target/test/index.test">;
}
