// flow-typed signature: 6c4f3fd94fbb1dfc43996de66e9c7919
// flow-typed version: <<STUB>>/@lugia/lugiax_v^1.0.1-2.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/lugiax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@lugia/lugiax" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@lugia/lugiax/flow-typed/npm/@lugia/lugiax-core_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/babel-jest_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/babel-preset-react-app_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/enzyme_v3.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/enzyme-adapter-react-16_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/flow-bin_v0.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/hoist-non-react-statics_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/immutable_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/jest_v20.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/react-dev-utils_vx.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/flow-typed/npm/react-test-renderer_v16.x.x" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/interface/lugiax.flow" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/lib/bind" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/lib/bindTo" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/lib/connect" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/lib/index" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/lib/utils" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/test/bind.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/test/bindTo.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/test/connect.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/test/import.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/test/login" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/test/user" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/test/utils" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/src/test/utils.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/interface/lugiax.flow" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/lib/bind" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/lib/bindTo" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/lib/connect" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/lib/index" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/lib/utils" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/test/bind.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/test/bindTo.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/test/connect.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/test/import.test" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/test/login" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/test/user" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/test/utils" {
  declare module.exports: any;
}

declare module "@lugia/lugiax/target/test/utils.test" {
  declare module.exports: any;
}

// Filename aliases
declare module "@lugia/lugiax/flow-typed/npm/@lugia/lugiax-core_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/@lugia/lugiax-core_vx.x.x"
  >;
}
declare module "@lugia/lugiax/flow-typed/npm/babel-jest_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/babel-jest_vx.x.x"
  >;
}
declare module "@lugia/lugiax/flow-typed/npm/babel-preset-react-app_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/babel-preset-react-app_vx.x.x"
  >;
}
declare module "@lugia/lugiax/flow-typed/npm/enzyme_v3.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/enzyme_v3.x.x"
  >;
}
declare module "@lugia/lugiax/flow-typed/npm/enzyme-adapter-react-16_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/enzyme-adapter-react-16_vx.x.x"
  >;
}
declare module "@lugia/lugiax/flow-typed/npm/flow-bin_v0.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/flow-bin_v0.x.x"
  >;
}
declare module "@lugia/lugiax/flow-typed/npm/hoist-non-react-statics_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/hoist-non-react-statics_vx.x.x"
  >;
}
declare module "@lugia/lugiax/flow-typed/npm/immutable_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/immutable_vx.x.x"
  >;
}
declare module "@lugia/lugiax/flow-typed/npm/jest_v20.x.x.js" {
  declare module.exports: $Exports<"@lugia/lugiax/flow-typed/npm/jest_v20.x.x">;
}
declare module "@lugia/lugiax/flow-typed/npm/react-dev-utils_vx.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/react-dev-utils_vx.x.x"
  >;
}
declare module "@lugia/lugiax/flow-typed/npm/react-test-renderer_v16.x.x.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/flow-typed/npm/react-test-renderer_v16.x.x"
  >;
}
declare module "@lugia/lugiax/src/interface/lugiax.flow.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/interface/lugiax.flow">;
}
declare module "@lugia/lugiax/src/lib/bind.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/lib/bind">;
}
declare module "@lugia/lugiax/src/lib/bindTo.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/lib/bindTo">;
}
declare module "@lugia/lugiax/src/lib/connect.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/lib/connect">;
}
declare module "@lugia/lugiax/src/lib/index.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/lib/index">;
}
declare module "@lugia/lugiax/src/lib/utils.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/lib/utils">;
}
declare module "@lugia/lugiax/src/test/bind.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/test/bind.test">;
}
declare module "@lugia/lugiax/src/test/bindTo.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/test/bindTo.test">;
}
declare module "@lugia/lugiax/src/test/connect.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/test/connect.test">;
}
declare module "@lugia/lugiax/src/test/import.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/test/import.test">;
}
declare module "@lugia/lugiax/src/test/login.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/test/login">;
}
declare module "@lugia/lugiax/src/test/user.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/test/user">;
}
declare module "@lugia/lugiax/src/test/utils.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/test/utils">;
}
declare module "@lugia/lugiax/src/test/utils.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/src/test/utils.test">;
}
declare module "@lugia/lugiax/target/interface/lugiax.flow.js" {
  declare module.exports: $Exports<
    "@lugia/lugiax/target/interface/lugiax.flow"
  >;
}
declare module "@lugia/lugiax/target/lib/bind.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/lib/bind">;
}
declare module "@lugia/lugiax/target/lib/bindTo.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/lib/bindTo">;
}
declare module "@lugia/lugiax/target/lib/connect.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/lib/connect">;
}
declare module "@lugia/lugiax/target/lib/index.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/lib/index">;
}
declare module "@lugia/lugiax/target/lib/utils.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/lib/utils">;
}
declare module "@lugia/lugiax/target/test/bind.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/test/bind.test">;
}
declare module "@lugia/lugiax/target/test/bindTo.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/test/bindTo.test">;
}
declare module "@lugia/lugiax/target/test/connect.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/test/connect.test">;
}
declare module "@lugia/lugiax/target/test/import.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/test/import.test">;
}
declare module "@lugia/lugiax/target/test/login.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/test/login">;
}
declare module "@lugia/lugiax/target/test/user.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/test/user">;
}
declare module "@lugia/lugiax/target/test/utils.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/test/utils">;
}
declare module "@lugia/lugiax/target/test/utils.test.js" {
  declare module.exports: $Exports<"@lugia/lugiax/target/test/utils.test">;
}
